# Generated by Django 5.1.3 on 2025-01-04 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0005_renomeartabelaarena'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arena',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Arena', 'verbose_name_plural': 'Arenas'},
        ),
        migrations.AlterField(
            model_name='arena',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arenas_cadastradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
