# Generated by Django 5.1.3 on 2025-01-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0007_jogo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jogo',
            new_name='Jogos',
        ),
    ]
