# Generated by Django 5.1.3 on 2025-01-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0010_alter_jogo_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='horario',
            field=models.TimeField(),
        ),
    ]
