# Generated by Django 5.1.3 on 2025-01-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0011_alter_jogo_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='horario',
        ),
    ]
