# Generated by Django 5.1.3 on 2025-01-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0012_remove_jogo_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='horario',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
