# Generated by Django 5.1.3 on 2025-01-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0013_jogo_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='horario',
            field=models.CharField(max_length=5),
        ),
    ]
