# Generated by Django 5.1.3 on 2025-01-10 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0015_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jogos_cadastrados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
