# Generated by Django 5.1.3 on 2025-01-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0016_jogo_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
