# Generated by Django 5.1.3 on 2025-01-15 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0017_delete_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='jogos_participando', to=settings.AUTH_USER_MODEL),
        ),
    ]
