# Generated by Django 5.1.3 on 2025-01-19 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0018_jogo_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='criador_jogo',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, related_name='jogos_criados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
