# Generated by Django 5.1.3 on 2025-01-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0019_jogo_criador_jogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='bolas',
            field=models.IntegerField(default=0, verbose_name='Quantidade de bolas de basquete disponíveis'),
        ),
    ]
