# Generated by Django 5.1.3 on 2025-01-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0020_jogo_bolas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='levar_bola',
            field=models.BooleanField(default=False, verbose_name='Levar bola'),
        ),
    ]
