# Generated by Django 5.1.3 on 2025-02-18 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0022_customuser_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='jogadores',
            field=models.ManyToManyField(blank=True, related_name='jogos', to=settings.AUTH_USER_MODEL),
        ),
    ]
