# Generated by Django 5.1.3 on 2025-02-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0023_jogo_jogadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='rachas/', verbose_name='Imagem do Racha'),
        ),
    ]
