# Generated by Django 5.1.3 on 2025-02-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0024_jogo_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='max_jogadores',
            field=models.IntegerField(default=2000, verbose_name='Quantidade máxima de jogadores'),
        ),
    ]
