# Generated by Django 5.1.3 on 2025-02-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0025_alter_jogo_max_jogadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='foto_quadra',
            field=models.ImageField(blank=True, null=True, upload_to='arenas/'),
        ),
    ]
