# Generated by Django 5.1.3 on 2025-02-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0026_arena_foto_quadra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arena',
            name='capacidade',
        ),
        migrations.RemoveField(
            model_name='arena',
            name='tipo_esporte',
        ),
    ]
