# Generated by Django 5.1.3 on 2025-02-22 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0027_remove_arena_capacidade_remove_arena_tipo_esporte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='jogo',
            options={'verbose_name': 'Racha', 'verbose_name_plural': 'Rachas'},
        ),
    ]
