# Generated by Django 5.1.3 on 2025-02-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0028_alter_customuser_options_alter_jogo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arena',
            options={'ordering': ['-data_cadastro'], 'permissions': [('can_add_arena', 'Can add new arena on map')], 'verbose_name': 'Arena', 'verbose_name_plural': 'Arenas'},
        ),
    ]
