# Generated by Django 5.1.3 on 2025-03-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0030_alter_arena_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da foto'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
