# Generated by Django 5.1.3 on 2025-03-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0031_customuser_foto_url_alter_customuser_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='foto_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da foto da quadra'),
        ),
    ]
