# Generated by Django 5.1.3 on 2025-03-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_synes', '0032_arena_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='foto_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da foto do racha'),
        ),
    ]
